# Generated by Django 4.2.16 on 2024-10-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_alter_productvariant_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
